### ISSUE TITLE
Cable Relief too long

### ISSUE THREAD

**Issue by Ramrawd** [thrutheframe/Tiki3#2]
Hi there, 

Really appreciate your work on this. 

On my setup with an ender 3 v2 the Cable Relief is too long for taller prints. It causes the cabling to get bunched up under the top bar and creates a lot of drag. 

I've designed a shorter version of this part in TinkerCad. It's pretty rough but it gets the job done. 

I also added a channel in the back for zip ties to go through. 

You may want to consider creating a shorter version of the cable guide for instances like mine.

Thanks! 
[3_2_Cable_relief_Short.zip](https://github.com/thrutheframe/Tiki3/files/7149001/3_2_Cable_relief_Short.zip)
![Capture](https://user-images.githubusercontent.com/48835880/132972235-a8a556c2-37c6-4583-a18a-d7696d13408b.JPG)

**Comment by thrutheframe** [comment]
Thank you for the feedback. I have designed a short version (20mm shorter) of the cable relief. I have not include the holes for the cable tie. This is because I want to reduce / eliminate as much overhangs or bridging in the design. 

The stl file can download it from the folder.
https://github.com/thrutheframe/Tiki3/tree/main/3_2%20other%20parts

**Comment by Ramrawd** [comment]
Perfect! Thanks so much for doing that!
